spring:
  application:
    name: one-to-one

  datasource:
    url: jdbc:mysql://localhost:3306/sb_aug_26
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
